#!/bin/sh

# @file clearwater-logging
#
# Copyright (C) 2013  Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by post at
# Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK

. /etc/clearwater/config

# Strip any existing clearwater-logging config.
touch /opt/splunkforwarder/etc/apps/search/local/outputs.conf
awk '/^#\+clearwater-logging$/,/^#-clearwater-logging$/ {next} {print}' /opt/splunkforwarder/etc/apps/search/local/outputs.conf >/tmp/outputs.conf.$$
mv /tmp/outputs.conf.$$ /opt/splunkforwarder/etc/apps/search/local/outputs.conf

# Now re-add it.
cat >>/opt/splunkforwarder/etc/apps/search/local/outputs.conf <<EOF
#+clearwater-logging
[tcpout]
defaultGroup = ${splunk_hostname}_9997

[tcpout:${splunk_hostname}_9997]
server = $splunk_hostname:9997

[tcpout-server://$splunk_hostname:9997]
#-clearwater-logging
EOF
